### PR TITLE
test(e2e): Add end-to-end tests for subscription partial updates

### LINKED ISSUE #3934: test(e2e): Add end-to-end test for subscription partial updates
## Background

PR #3930 implemented server-side partial row updates for subscription UPDATE deltas, using the `SubscriptionPartialData` (0xF7) message format. PR #3870 added client-side support for receiving these messages.

However, there's no end-to-end test verifying the complete flow works correctly.

## Proposed Test

Create an integration test that:

1. Sets up a subscription on a table with multiple columns
2. Performs an UPDATE that changes only 1-2 columns
3. Verifies the client receives a `SubscriptionPartialData` message (not full row)
4. Verifies the client correctly applies the partial update to its local state
5. Verifies the client's row state matches the expected values

## Test Scenarios

- [ ] Single column change produces partial update
- [ ] PK columns are included even when unchanged
- [ ] Update changing >50% of columns falls back to full row
- [ ] NULL value changes are handled correctly
- [ ] Multiple rows updated in single transaction

## Related

- #3903 (Parent issue)
- #3930 (Server-side partial updates)
- #3870 (Client-side partial update support)

## Dependencies

- [ ] PR #3930: Server-side partial row updates must be merged first

This test validates functionality introduced in PR #3930. Implementation can begin once that PR is merged.

---
*Enhanced by Curator: Added implementation guidance, wire format reference, and dependency tracking.*

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

- Adds comprehensive e2e tests for `SubscriptionPartialData` (0xF7) message flow
- Tests NULL value handling in partial updates (non-NULL → NULL and NULL → non-NULL)
- Verifies actual data values from 0xF7 message payloads, not just message types
- Implements full end-to-end flow test covering subscription setup, partial updates, column mask verification, and final state confirmation

## Tests Added

| Test | Description |
|------|-------------|
| `test_partial_data_null_value_changes` | Verifies partial updates correctly handle NULL value changes |
| `test_partial_data_verifies_actual_values` | Parses and validates actual data values from 0xF7 payloads |
| `test_e2e_subscription_partial_update_client_state` | Full e2e flow: subscribe → update → verify 0xF7 → check values → confirm state |

## Test Plan

- [x] New tests compile without errors
- [x] All 19 e2e subscription tests pass
- [x] Tests validate the scenarios from issue #3934

Closes #3934

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rjwalters** [comment]
✅ **Review feedback addressed:**

1. **Rebased onto main** - Removed unrelated web-demo changes (commit `2bd668bb` was skipped as already merged to main in `6a5c0ea2`)

2. **Fixed Arc<str> compilation errors** - Updated tests to use `Arc::from("...")` instead of `"...".to_string()` to match the API change from PR #3904

**Changes summary:**
- Branch now only contains `e2e_subscription_tests.rs` changes (1 file)
- All 7 `partial_row_delta` unit tests pass
- Tests compile cleanly with the `Arc<str>` changes

Ready for re-review!
