### PR TITLE
fix(server): Remove duplicate send_subscription_partial_data method

### LINKED ISSUE #3929: test: Add test coverage for UPDATE + columnar cache invalidation
## Summary

There are no explicit tests verifying that UPDATE operations correctly invalidate the columnar cache.

## Context

PRs #3910 and #3928 added test coverage for REPLACE and DELETE operations invalidating the columnar cache. However, UPDATE operations also call `invalidate_columnar_cache()` (at `crates/vibesql-executor/src/update/mod.rs:346`) but lack dedicated test coverage.

## Proposed Test

Add a test that:
1. Creates a table and populates it with data
2. Warms the columnar cache via `database.get_columnar()` or `pre_warm_columnar_cache()`
3. Executes an UPDATE statement that modifies rows
4. Verifies the columnar cache returns the correct data (updated values should appear)

## Location

The test should be added to a new file:
- `crates/vibesql-executor/tests/update_columnar_cache_tests.rs`

## Related

- REPLACE test coverage: #3891, PR #3910
- DELETE test coverage: #3912, PR #3928
- Original cache bug: #3884

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary
- Fixes duplicate method definition in ConnectionHandler that was causing compilation errors
- PR #3930 accidentally added a second `send_subscription_partial_data` method
- Removes the duplicate while keeping the original which includes observability metrics

Note: Issue #3929 requested test coverage for UPDATE + columnar cache invalidation, but these tests already exist (added by PR #3926). This PR fixes the compilation error discovered while verifying those tests work.

## Test plan
- [x] `cargo test -p vibesql-executor --test update_columnar_cache_tests` - 6/6 tests pass
- [x] Compilation succeeds without duplicate definition error

Closes #3929

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rjwalters** [comment]
✅ **Approved!**

Code review complete. This is a clean fix for the duplicate method definition introduced by PR #3930.

**Verified:**
- ✅ Compilation succeeds with `cargo check -p vibesql-server`
- ✅ All 6 tests pass in `cargo test -p vibesql-executor --test update_columnar_cache_tests`
- ✅ The correct method is retained (line 1517-1530, which includes observability metrics)
- ✅ The duplicate (line 1550-1558, without metrics) is properly removed
- ✅ PR description correctly uses "Closes #3929" for auto-close

The fix is minimal and correctly targeted. Good catch on the duplicate definition from the merge!
