### PR TITLE
test(tcl): mark hiddencolumns capability as unsupported

### LINKED ISSUE #5083: TCL triggerupfrom: declare hiddencolumns capability unsupported in TCL shim
## Background

This is sub-issue **C** (of 3) split out from #5073. Sub-issue **A** (SQL-dump trigger persistence) is being addressed in the parent PR.

## Problem

`scripts/tester_vibesql.tcl:3895-3913` declares `unsupported_caps` for the `ifcapable` directive but does **not** list `hiddencolumns`. As a result, \`ifcapable hiddencolumns\` evaluates to true and the \`-hc-enabled\` test variant runs against VibeSQL.

VibeSQL does not actually suppress columns named \`__hidden__*\` from \`SELECT *\`, so the result includes them and the test fails with extra columns:

\`\`\`
Expected: a 1 b 2 c 3 d 4
Got:      a 1 one b 2 two c 3 three d 4 four
\`\`\`

## Two Possible Fixes

**Cheap (preferred for now):** Declare \`hiddencolumns\` unsupported in the TCL shim. The corresponding \`-hc-disabled\` variant runs and VibeSQL passes it.

**Expensive (out of scope):** Implement the actual hidden-column behavior (suppress columns prefixed with \`__hidden__\` from \`SELECT *\`). This is a larger SQLite-specific feature that probably belongs in its own dedicated issue.

## Files Touched

- \`scripts/tester_vibesql.tcl:3897\` — add \`hiddencolumns\` to \`unsupported_caps\` list

## Tests Newly Unblocked

- \`triggerupfrom 4.1-hc-enabled\` skipped; \`4.1-hc-disabled\` runs and passes

## Acceptance Criteria

- [ ] \`triggerupfrom 4.1-hc-enabled\` is skipped
- [ ] \`triggerupfrom 4.1-hc-disabled\` runs and passes
- [ ] No regression in other \`ifcapable\` tests

## Context

Discovered during curation of #5073. See [curator analysis comment](https://github.com/rjwalters/vibesql/issues/5073#issuecomment-4358291260) for full details.

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

Append `hiddencolumns` to the `unsupported_caps` list in `scripts/tester_vibesql.tcl` so the TCL shim correctly reports it as unsupported. VibeSQL does not implement SQLite's hidden column suppression from `SELECT *`, so test files using `ifcapable hiddencolumns` should take the `-hc-disabled` branch.

## Changes

- `scripts/tester_vibesql.tcl:3913` — added `hiddencolumns` to `unsupported_caps`

## Test plan

- [x] `./scripts/tcltest run --pattern "triggerupfrom.test"` — `4.1-hc-enabled` no longer in failure list (now skipped, `4.1-hc-disabled` runs and passes)
- [x] Other failures in this file (1.1, 1.2, 1.3, 2.3, 4.3) are pre-existing and unrelated to this change

Closes #5083

### CODE REVIEW

**Comment by rjwalters** [comment]
## Judge Review: APPROVED

**Verdict**: Approved — minimal, correct, zero-regression-risk one-token edit.

### Verification
- Diff is exactly the addition of `hiddencolumns` to the `set unsupported_caps {...}` list at `scripts/tester_vibesql.tcl:3913` — no other changes
- Line is correctly inside the `check_single_capability` proc, where `unsupported_caps` is defined
- PR body includes `Closes #5083`
- Semantically correct: VibeSQL does not implement SQLite's `SELECT *` hidden-column suppression, so `ifcapable hiddencolumns` should evaluate false and tests should take the `-hc-disabled` branch
- Test plan documents that `triggerupfrom.test 4.1-hc-enabled` is now skipped (passes), with remaining failures explicitly called out as pre-existing and unrelated

### Notes
- Scope discipline is exemplary: single-token addition addressing exactly the failure case described in #5083
- Pre-existing failures in `triggerupfrom.test` (1.1, 1.2, 1.3, 2.3, 4.3) correctly left out of scope

Promoting to `loom:pr` for human merge.

🤖 Reviewed by Loom Judge
