### PR TITLE
fix(pragma): resolve $arr(elem) TCL binding + composite-PK table_info positions

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

Two in-scope SQLite PRAGMA-introspection conformance fixes, advancing `pragma.test` from **40 -> 46 passing** (149 -> 143 failing, 0 regressions). Part of the PRAGMA family in #6175 (epic #5779). Builds on the `sql_source` rehydrate pattern from #6209.

## Changes

- **TCL shim (`scripts/tester_vibesql.tcl`)**: `substitute_tcl_vars` now resolves `$arr(elem)` array-element parameter references the way SQLite's TCL binding does. `capture_pragma` iterates a PRAGMA with `db eval $sql x {...}` (populating `x(colname)`) and then builds `INSERT INTO out VALUES($x(seq),$x(name),...)`. Previously the literal `$x(seq)` reached VibeSQL and the parser rejected it (`near "(": syntax error`). The new pass runs *before* the plain `$var` pass and only substitutes when the array element actually resolves in scope, so ordinary text is untouched. The introspection PRAGMA output itself was already correct.
- **Engine (`crates/vibesql-cli/src/executor/mod.rs`)**: `PRAGMA table_info` `pk` column now honors SQLite's duplicate-column-consumes-a-position rule for a declared composite PRIMARY KEY. `PRIMARY KEY(a,b,a,c)` reports a=1, b=2, c=4 (the repeated `a` consumes ordinal 3). VibeSQL's catalog `primary_key` list is de-duplicated and loses that gap, so the ordinals are recovered from the re-parsed table-level PK constraint; the catalog-derived map remains the fallback. pk lookups are now case-insensitive.
- **Tests (`crates/vibesql-cli/src/executor/tests.rs`)**: two focused unit tests for the normal and duplicate-column composite-PK cases.

## Acceptance Criteria Verification

| Criterion | Status | Verification |
|-----------|--------|--------------|
| Fix a coherent in-scope introspection slice | ✅ | capture_pragma dynamic-SQL binding + composite-PK positions |
| Real test movement, no regressions | ✅ | pragma.test 40->46; diffed before/after failing sets — 4 flipped (6.4, 6.5.1, 6.5.1b, 6.8), 0 newly failing |
| Introspection PRAGMAs stay green | ✅ | index_list/index_info output verified correct pre- and post-change |
| No engine regressions | ✅ | `cargo test --release -p vibesql-cli` — 166 lib tests + all integration suites green |
| Bucket-A pragmas not forced green | ✅ | cache_size/synchronous/lock_status left failing; routed to #6154 |

## Tests flipped to passing (pragma.test)

- `pragma-6.4` — `capture_pragma` + `index_list(t3)`
- `pragma-6.5.1` / `pragma-6.5.1b` — `capture_pragma` + `index_info`/`index_xinfo`
- `pragma-6.8` — composite-PK duplicate-column `pk` position

## Routing (not fixed here)

- **Bucket-A -> #6154** (pager/journal internals, deliberately not forced green): `cache_size`/`default_cache_size` (pragma-1.*), `synchronous` (pragma-5.*), `lock_status` (pragma-7.3), `freelist_count`/`cache_spill` (pragma2.*).
- **In-scope follow-up increments**: verbatim declared-type preservation for `VARCHAR(45, 65)` and `X'abcdef'` default text (pragma-6.7 — current `type_source` includes `[]`/`""` delimiters so a naive verbatim echo would regress pragma-6.2); temp/main schema-qualified table resolution (pragma-6.6.3/6.6.4); raw-protocol NULL-vs-empty rendering in the shim (pragma-6.2.2).

## Test Plan

- `cargo test --release -p vibesql-cli` — all green (166 lib tests incl. 2 new).
- `make test-tcl-file FILE=pragma.test` — 46 passed / 143 failed (was 40 / 149); before/after failing-set diff shows 0 regressions.
- Ran `select4.test` (123/0), `where2.test` (30/0), `index.test` (69/1, the single failure `index-23.1 datatype mismatch` is pre-existing and unrelated to array binding) to confirm the shim change causes no regressions in files using `$arr(elem)` binding.

Part of #6175

### CODE REVIEW

**Comment by rjwalters** [comment]
Merge conflict with `main` resolved (Doctor).

**What conflicted:** After #6219 landed on main, merging main into this branch produced one content conflict in `crates/vibesql-cli/src/executor/tests.rs` — both sides appended new `#[test]` functions at the same spot (this branch's two composite-PK `table_info` regression tests vs. main's neighboring pragma tests). `scripts/tester_vibesql.tcl` auto-merged cleanly, so no manual shim merge was needed.

**How resolved:** Kept both sides — this branch's `test_pragma_table_info_composite_pk_positions` and `test_pragma_table_info_composite_pk_duplicate_column_gap` were preserved alongside main's tests. Confirmed both TCL-shim changes survive in `tester_vibesql.tcl`: main's lexer "unrecognized token" error translation (#6219, ~line 683) and this branch's `$arr(elem)` array-element binding substitution in `substitute_tcl_vars` (~line 1216). No conflict markers remain anywhere in the tree.

**Verification:**
- `cargo build --release` — clean
- `cargo test --release -p vibesql-cli` (full, unfiltered) — all green, 0 failures
- TCL `select4.test` — 123/123 (100%), confirms shim works on a plain file
- TCL `pragma.test` — runs to completion (46 passed); remaining failures are the pre-existing unsupported-pragma set, not a regression from this merge

PR is now MERGEABLE and remains `loom:review-requested`.

**Comment by rjwalters** [comment]
❌ **Changes Requested — merge duplicated a code block; re-verification needed on the merged head**

The code changes themselves are well-designed, but the merge commit `db8dc8c7d` (resolving the conflict with origin/main / #6209) botched the conflict resolution and **duplicated the `decl_facts` computation** in `crates/vibesql-cli/src/executor/mod.rs`.

**What's wrong**

Your clean commit `e379612e3` had a single combined block that computes both `decl_facts` and `pk_source_positions`. The merged head now has **two** `decl_facts` bindings:

- `let mut decl_facts` at ~line 2022 (your combined block — computes `decl_facts` + `pk_source_positions`)
- `let decl_facts: … = { … }` at ~line 2106 (the pre-existing #6209 block, re-added by the merge)

The second binding **shadows** the first, so:
1. The `CREATE TABLE` `sql_source` is re-parsed twice per `PRAGMA table_info`.
2. The first `decl_facts` map is fully populated and then never read (dead code). Only `pk_source_positions` from the first block survives.

Behavior is still correct (both maps are identical), and it compiles (the `.insert()` calls keep the first binding from tripping `unused_variables`), so this is not a functional bug — but it is dead/duplicated code from a bad merge that should not land.

**Fix**

Delete the second, shadowing `decl_facts` block (the `let decl_facts: std::collections::HashMap<String, (bool, bool)> = { … };` at ~line 2106). The first combined block already produces the identical map, and the loop below will then read it directly.

**Re-verify on the merged head**

The PR's acceptance numbers (166 lib tests green, `pragma.test` 40→46, 0 regressions) were measured on the **pre-merge** commit `e379612e3`. After removing the duplicate block, please re-run on the actual merged head and update the PR:
- `cargo test --release -p vibesql-cli`
- `make test-tcl-file FILE=pragma.test`

**What looks good (no changes needed here)**
- TCL shim `$arr(elem)` substitution (`scripts/tester_vibesql.tcl`): correct and safe — it runs before the plain `$var` pass and only substitutes when the array element actually resolves in scope (`found=1`); otherwise it breaks and leaves the text untouched, so ordinary SQL containing `$`/parens is never corrupted. Termination is guaranteed (`format_sql_value` always changes the string on a hit; regexp miss breaks the loop).
- Composite-PK ordinal logic: the duplicate-consumes-a-position rule is implemented correctly (`or_insert` keeps first occurrence while `idx` still advances → `PRIMARY KEY(a,b,a,c)` = a1/b2/c4), keys are lowercased for case-insensitive matching, and single-column column-level PKs correctly fall through to the catalog map (position 1). The `sql_source` rehydrate fallback is safe (None/parse-failure/`AS SELECT` → catalog-derived behavior, unchanged).
- Bucket-A routing is legitimate: `cache_size`/`default_cache_size`/`synchronous`/`lock_status`/`freelist_count`/`cache_spill` are genuine pager/journal/cache internals, not introspection pragmas. No introspection pragma was silently dropped or force-greened.
- The two new unit tests cover the normal and duplicate-column composite-PK cases well.

The partial-increment scope (Part of #6175) is fine — not requesting the family be completed here.

Note: the `test` CI job was still running at review time; please confirm all checks are green after the fix.

**Comment by rjwalters** [comment]
## Doctor: duplicate `decl_facts` block removed

Fixed the single blocking defect from Judge review. The conflict-resolution merge `db8dc8c7d` had duplicated the `decl_facts` computation in `PRAGMA table_info` handling (`crates/vibesql-cli/src/executor/mod.rs`), leaving a second shadowing `let decl_facts` (~line 2106) that re-parsed the CREATE TABLE source on every call — dead double-parse work.

**Fix (`ceb6b4b41`):** deleted the redundant shadowing block plus its duplicated doc comment (former lines 2087–2131). The surviving block is the live one that also derives `pk_source_positions` (used at `pk_positions`), so composite-PK ordinal behavior is preserved. The affected region now matches the author's clean pre-merge commit `e379612e3` byte-for-byte — exactly one `decl_facts`, no behavior change.

**Verification on the merged head:**
- `cargo build --release -p vibesql-cli`: warning-clean, no unused-variable warning
- `cargo test --release -p vibesql-cli` (full, unfiltered): **all green** (166 + 10 + 8 + 8 + 5 + 4 + 3 + 2 + doc-tests, 0 failed)
- `pragma.test`: **46 passing** (unchanged post-fix count; remaining failures are pre-existing unimplemented TCL helpers like `delete_file`/`hexio_write`)
- `select4.test`: **123/123 (100%)** — shim $arr(elem) binding confirmed

Scope: only the duplicate block was touched. Back to `loom:review-requested` and MERGEABLE.

**Comment by rjwalters** [comment]
## Judge: APPROVED (follow-up re-review)

Focused re-review of the Doctor fix (commit `ceb6b4b41`) that removed the duplicated `decl_facts` block from the botched conflict-resolution merge (`db8dc8c7d`).

**Defect resolved.** Exactly one `decl_facts` declaration remains in `crates/vibesql-cli/src/executor/mod.rs` (line 2024), and it is the live one — read downstream at line 2053 to drive the `type`/`notnull` columns. The shadowing second block and its redundant per-call CREATE TABLE re-parse are gone. Verified the region is now **byte-for-byte identical to the clean pre-merge commit `e379612e3`** (`git diff e379612e3 <head>` on mod.rs is empty).

**No unrelated churn.** Diff vs main is confined to the three already-approved files/changes: `scripts/tester_vibesql.tcl` (shim `$arr(elem)` binding), `executor/mod.rs` composite-PK ordinals (`pk_positions` at line 1997, read at 2093, intact), and `executor/tests.rs` unit tests. Not re-litigating the approved substance.

**CI green.** All 5 checks pass on head `ceb6b4b41`: test (32m44s), storage-features-check, verify-benchmark-queries, wasm-check, web-demo-lockfile. Merge state CLEAN / MERGEABLE.

Approving. Handing off to merge queue.
