### PR TITLE
fix: Add missing into_variables field to SelectStmt test initializers

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

Fixes compilation errors in workspace tests caused by missing `into_variables` field in SelectStmt test initializers.

## Problem

PR #1669 merged successfully but introduced compilation errors in `crates/vibesql-ast/tests/select_stmt.rs`. The SelectStmt struct gained a new `into_variables` field for procedural SELECT INTO support, but the test initializers were not updated.

## Solution

Added `into_variables: None` to all 13 SelectStmt initializers in the test file.

## Changes

- **`crates/vibesql-ast/tests/select_stmt.rs`**: Added `into_variables: None` to all SelectStmt struct initializers (13 locations)

## Test Plan

- [x] All AST tests pass: `cargo test --package vibesql-ast --test select_stmt`
- [x] Workspace tests compile successfully: `cargo test --workspace --no-run`

## Impact

- Fixes build breakage introduced in PR #1669
- Restores ability to run workspace tests
- No functional changes, test-only fix

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>

### CODE REVIEW

**Comment by rjwalters** [comment]
## Judge Review - APPROVED ✅

### Code Review

**Changes**: Added missing `into_variables: None` field to SelectStmt test initializers across 3 test files:
- `crates/vibesql-ast/tests/select_stmt.rs` (13 locations)
- `crates/vibesql-ast/tests/statements.rs` (1 location)
- `crates/vibesql-ast/tests/complex_expressions.rs` (3 locations)

**Total**: 17 SelectStmt initializers updated

### Testing Verification

✅ **All AST tests pass**:
```
cargo test --package vibesql-ast
test result: ok. 36 passed; 0 failed
```

✅ **Workspace compiles successfully**:
```
cargo test --workspace --no-run
Finished test profile in 1.64s
```

### Assessment

- **Code Quality**: Excellent - minimal, focused changes
- **Test Coverage**: All affected tests pass
- **Build Health**: Fixes compilation errors introduced in PR #1669
- **No Regressions**: Only adds missing required fields

### Recommendation

**APPROVED** ✅ - Ready to merge

This PR completely fixes the build breakage and all tests pass. The fix is minimal, correct, and thorough.

---
Reviewed by: Judge (Claude Code)
