### PR TITLE
Refactor: Split aggregate_distinct tests (552 lines)

### LINKED ISSUE #441: Refactor: Split aggregate_distinct tests (552 lines)
## Problem
The test file `crates/executor/src/tests/aggregate_distinct.rs` has grown to 552 lines, making it difficult to navigate and maintain.

## Proposal
Split this test file into smaller, focused test modules organized by:
- COUNT DISTINCT tests
- SUM DISTINCT tests
- AVG DISTINCT tests
- Multiple DISTINCT in same query tests
- DISTINCT with GROUP BY tests
- DISTINCT with complex expressions

## Benefits
- Improved test organization
- Faster test file navigation
- Easier to locate specific test cases
- Better parallel test execution potential

## File Location
`crates/executor/src/tests/aggregate_distinct.rs` (552 lines)

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary
Refactored the 552-line `aggregate_distinct.rs` test file into smaller, focused modules organized by aggregate function type. This improves maintainability and makes it easier to navigate the test suite.

## Changes
- Created `aggregate_distinct/` subdirectory with 5 focused modules:
  - `count_distinct.rs`: Tests for COUNT DISTINCT (3 tests)
  - `sum_distinct.rs`: Tests for SUM DISTINCT (2 tests)
  - `avg_distinct.rs`: Tests for AVG DISTINCT (1 test)
  - `min_max_distinct.rs`: Tests for MIN/MAX DISTINCT (2 tests)
  - `edge_cases.rs`: NULL handling, single value, empty table tests (2 tests)
- Moved shared helper `create_test_db_with_duplicates()` to `aggregate_distinct/mod.rs`
- Deleted original monolithic `aggregate_distinct.rs` file

## Test Plan
- ✅ All 10 aggregate_distinct tests pass (verified with `cargo test -p executor --lib`)
- ✅ Total test suite passes: 228 tests passed, 0 failed
- ✅ Test count matches original: 10 tests total

## Verification
```bash
$ cargo test -p executor --lib | grep aggregate_distinct
test tests::aggregate_distinct::avg_distinct::test_avg_distinct ... ok
test tests::aggregate_distinct::count_distinct::test_count_distinct_basic ... ok
test tests::aggregate_distinct::count_distinct::test_count_distinct_vs_count_all ... ok
test tests::aggregate_distinct::count_distinct::test_count_distinct_with_nulls ... ok
test tests::aggregate_distinct::sum_distinct::test_sum_distinct ... ok
test tests::aggregate_distinct::sum_distinct::test_sum_distinct_vs_sum_all ... ok
test tests::aggregate_distinct::min_max_distinct::test_min_distinct ... ok
test tests::aggregate_distinct::min_max_distinct::test_max_distinct ... ok
test tests::aggregate_distinct::edge_cases::test_distinct_all_same_value ... ok
test tests::aggregate_distinct::edge_cases::test_distinct_empty_table ... ok
```

Closes #441

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>

### CODE REVIEW

**Comment by rjwalters** [comment]
🔧 Fixed compilation errors by rebasing onto main branch

The branch was behind main and CI was failing due to merge conflicts with the duplicate `Default` variant that was recently fixed in commit 3cb7610.

**Changes made:**
- Rebased `feature/issue-441` onto `origin/main`
- Resolved merge conflicts automatically during rebase
- Verified all aggregate_distinct tests pass locally (10/10 tests ✅)

CI should now pass. All 10 aggregate_distinct tests verified working.

**Comment by rjwalters** [comment]
🔧 Fixed parser test failures

The 3 failing parser tests were due to PR #427 changing how CURRENT_DATE/TIME/TIMESTAMP are represented in the AST. They were changed from Function expressions to dedicated expression variants with optional precision support.

**Test fixes:**
- `test_parse_select_current_date`: Now expects `CurrentDate` variant
- `test_parse_select_current_time`: Now expects `CurrentTime{precision}` variant  
- `test_parse_select_current_timestamp`: Now expects `CurrentTimestamp{precision}` variant

All tests now pass locally (454/454). CI should be fully green now! ✅
