### ISSUE TITLE
Fix CI compilation failures after merge

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/vibesql#610]
Recent merge introduced several compilation errors that broke CI:

## Issues Fixed

1. **Missing QualifiedWildcard match arms**: The addition of qualified asterisk support (table.*) in SELECT statements required updating all match statements on SelectItem enum to handle the new QualifiedWildcard variant.

2. **PrivilegeType enum changes**: UPDATE and REFERENCES privileges now take optional column lists as parameters. Tests needed to be updated from PrivilegeType::Update to PrivilegeType::Update(None).

3. **Schema parsing regression**: parse_qualified_identifier function didn't allow keywords as identifiers. Modified to accept Token::Keyword variants for cases like CREATE SCHEMA catalog.test_schema.

## Files Modified

- crates/executor/src/select_into.rs - Added QualifiedWildcard case
- examples/batch_results_generator.rs - Added QualifiedWildcard case  
- examples/query_runner.rs - Added QualifiedWildcard case
- tests/grant_tests.rs - Updated PrivilegeType usage
- tests/test_revoke_privileges.rs - Updated PrivilegeType usage
- crates/parser/src/parser/helpers.rs - Modified parse_qualified_identifier to accept keywords

## Tests Status

All core tests now pass. The web demo examples test still fails but appears to be due to missing test data setup rather than compilation issues.
