### PR TITLE
feat: Add support for COMMENT clause on column definitions

### LINKED ISSUE #796: Investigate failing SQLLogicTest: MULTIPOLYGON data type with COMMENT clause
## Summary

The SQLLogicTest suite currently has at least one failing test file related to parsing the MULTIPOLYGON data type, particularly when used with the COMMENT clause on column definitions.

## Failing Test

**File**: `ddl/createtable/createtable1.test`

**Error**: 
```
Parse error: ParseError { message: "Unknown data type: MULTIPOLYGON" }
```

**Failing SQL**:
```sql
CREATE TABLE `t1710a` (
  `c1` MULTIPOLYGON COMMENT 'text155459', 
  `c2` MULTIPOLYGON COMMENT 'text155461'
);
```

## Analysis Results

From the latest test run:
- Total test files: 9
- Passed: 8 (88.9%)
- Failed: 1 (11.1%)

## Investigation Needed

1. **MULTIPOLYGON data type**: Determine if this is a spatial/geometric data type that needs to be implemented
2. **COMMENT clause**: Verify that column-level COMMENT syntax is properly supported in CREATE TABLE statements
3. **Parser behavior**: The error suggests the parser may be encountering the COMMENT keyword unexpectedly when parsing the column definition

## Related

This may be related to:
- Spatial data type support (MULTIPOLYGON, POLYGON, POINT, etc.)
- Column attribute parsing (COMMENT, DEFAULT, constraints, etc.)

## Acceptance Criteria

- [ ] Identify root cause of MULTIPOLYGON parse error
- [ ] Determine if MULTIPOLYGON support is needed or if test should be skipped
- [ ] Verify COMMENT clause parsing works correctly on column definitions
- [ ] Fix parser or add appropriate feature support
- [ ] Test passes or is appropriately marked as vendor-specific/skipped

## Test Command

```bash
cargo test --test sqllogictest_suite --release -- --nocapture 2>&1 | python3 scripts/analyze_sqllogictest.py
```

### PR DESCRIPTION
**Pull request by rjwalters**
This PR adds support for the COMMENT clause on column definitions in CREATE TABLE statements.

## Changes

- Added  field to  AST struct
- Modified parser to recognize and parse  syntax after column data types
- Added  as a keyword in the lexer
- Updated all  instantiations throughout the codebase
- Fixed failing SQLLogicTest case for MULTIPOLYGON with COMMENT

## Test Case

The parser now correctly handles SQL like:

## Closes

Closes #796

### CODE REVIEW

**Comment by rjwalters** [comment]
✅ Review feedback addressed:

**Changes made:**
- Swapped parse order: DEFAULT now parsed BEFORE COMMENT (per MySQL 8.4 standard)
- Added test case: `CREATE TABLE t (col INT DEFAULT 5 COMMENT 'test column');`
- Verified existing COMMENT test still passes (`test_sqllogictest_multipolygon_with_comment`)

**Test results:**
✅ `test_default_before_comment_mysql_standard` - PASSED
✅ `test_sqllogictest_multipolygon_with_comment` - PASSED

**Files modified:**
- `crates/parser/src/parser/create/table.rs` - Reordered parsing logic (lines 51-72)
- `crates/parser/src/tests/create_table/data_types.rs` - Added new test case

The parser now correctly handles the MySQL standard order where DEFAULT comes before COMMENT. Ready for re-review!

**Comment by rjwalters** [comment]
✅ **Approved!**

This PR successfully implements the COMMENT clause for column definitions in CREATE TABLE statements, resolving issue #796.

## Code Review Summary

### Implementation Quality ✅

**AST Changes:**
- Added `comment: Option<String>` field to `ColumnDef` struct (crates/ast/src/ddl/table.rs:36)
- Clean, straightforward data model change

**Parser Changes:**
- Added `Comment` keyword to lexer and keyword enums ✅
- Parser correctly handles COMMENT clause after DEFAULT (follows MySQL standard ordering) (crates/parser/src/parser/create/table.rs:59-72)
- Proper error handling for missing string literal after COMMENT
- All existing `ColumnDef` instantiations updated with `comment: None` (select_into.rs:106, alter.rs:129)

**Test Coverage:**
- Comprehensive test for MULTIPOLYGON with COMMENT (test_sqllogictest_multipolygon_with_comment) ✅
- Test for DEFAULT before COMMENT ordering (test_default_before_comment_mysql_standard) ✅
- All 59 CREATE TABLE tests pass ✅
- All 15 ALTER TABLE tests pass ✅

### Design Correctness ✅

- Follows MySQL standard: `DEFAULT` before `COMMENT` clause
- Proper integration with existing parsing infrastructure
- No breaking changes to existing code
- Comment field is optional (None for ALTER TABLE, SELECT INTO)

### Documentation ✅

- PR description includes clear example SQL
- Code comments explain MySQL standard ordering
- Test names are descriptive

## Local Testing Results

```
✅ test_sqllogictest_multipolygon_with_comment ... ok
✅ test_default_before_comment_mysql_standard ... ok
✅ All 59 CREATE TABLE tests pass
✅ All 15 ALTER TABLE tests pass
```

## CI Status Note

The CI failure in `test_update_hash_indexes.rs` is **unrelated to this PR**. This test:
- Is NOT modified by this PR (verified with `gh pr diff 802 --name-only`)
- Fails on main branch due to `TableSchema` constructor changes (from PR #801)
- Is a pre-existing compilation error that needs a separate fix

This COMMENT feature implementation is ready to merge.

## Recommendation

**Approve and merge.** The COMMENT clause implementation is clean, well-tested, and follows SQL standards. The CI failure is a pre-existing issue on main that should be addressed in a separate PR/issue.
