### ISSUE TITLE
refactor: Fix IndexData encapsulation violations in executor (Phase 1)

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/vibesql#1501]
## Overview

Fix encapsulation violations where executor code directly accesses the `.data` field of `IndexData`, preventing the enum-based architecture from working properly.

## Problem

The `IndexData` enum was introduced in commit 85c82c72 to support both in-memory and disk-backed indexes:

```rust
pub enum IndexData {
    InMemory { data: BTreeMap<Vec<SqlValue>, Vec<usize>> },
    DiskBacked { btree: Arc<BTreeIndex>, buffer_pool: Arc<BufferPool> },
}
```

However, executor code still directly accesses the `.data` field, which only works for the `InMemory` variant. **Four violations found:**

**Violation 1**: `crates/vibesql-executor/src/select/executor/index_optimization/order_by.rs:132`
```rust
index_data.data.iter()  // ❌ Direct field access
```

**Violation 2**: `crates/vibesql-executor/src/select/executor/index_optimization/where_filter.rs:112`
```rust
index_data.data.get(&search_key)  // ❌ Direct field access
```

**Violation 3**: `crates/vibesql-executor/src/update/constraints.rs:96`
```rust
index_data.data.contains_key(&new_key_values)  // ❌ Direct field access
```

**Violation 4**: `crates/vibesql-executor/src/insert/constraints.rs:210`
```rust
index_data.data.contains_key(&key_values)  // ❌ Direct field access
```

**Impact**: Cannot switch to `DiskBacked` variant without compilation errors.

## Solution

Add proper API methods to `IndexData` and update all callsites to use them.

### 1. Add methods to IndexData (in `crates/vibesql-storage/src/database/indexes.rs`)

```rust
impl IndexData {
    /// Get all key-value pairs as an iterator
    pub fn iter(&self) -> Box<dyn Iterator<Item = (&Vec<SqlValue>, &Vec<usize>)> + '_> {
        match self {
            IndexData::InMemory { data } => Box::new(data.iter()),
            IndexData::DiskBacked { .. } => {
                // TODO: Implement when DiskBacked is active
                unimplemented\!("DiskBacked iteration not yet implemented")
            }
        }
    }
    
    /// Lookup exact key
    pub fn get(&self, key: &[SqlValue]) -> Option<&Vec<usize>> {
        match self {
            IndexData::InMemory { data } => data.get(key),
            IndexData::DiskBacked { .. } => {
                // TODO: Implement when DiskBacked is active
                unimplemented\!("DiskBacked lookup not yet implemented")
            }
        }
    }
    
    /// Check if key exists in index
    pub fn contains_key(&self, key: &[SqlValue]) -> bool {
        match self {
            IndexData::InMemory { data } => data.contains_key(key),
            IndexData::DiskBacked { .. } => {
                // TODO: Implement when DiskBacked is active
                unimplemented\!("DiskBacked contains_key not yet implemented")
            }
        }
    }
}
```

### 2. Update order_by.rs (line 132)

```rust
// Before
let mut data_vec: Vec<(Vec<SqlValue>, Vec<usize>)> =
    index_data.data.iter().map(|(k, v)| (k.clone(), v.clone())).collect();

// After
let mut data_vec: Vec<(Vec<SqlValue>, Vec<usize>)> =
    index_data.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
```

### 3. Update where_filter.rs (line 112)

```rust
// Before
index_data.data.get(&search_key).cloned().unwrap_or_else(Vec::new)

// After
index_data.get(&search_key).cloned().unwrap_or_else(Vec::new)
```

### 4. Update update/constraints.rs (line 96)

```rust
// Before
if index_data.data.contains_key(&new_key_values) {

// After
if index_data.contains_key(&new_key_values) {
```

### 5. Update insert/constraints.rs (line 210)

```rust
// Before
if index_data.data.contains_key(&key_values) {

// After
if index_data.contains_key(&key_values) {
```

## Acceptance Criteria

- [ ] `IndexData` has `iter()`, `get()`, and `contains_key()` methods
- [ ] No direct `.data` field accesses in `crates/vibesql-executor/` (verified via grep)
- [ ] All existing tests pass (`cargo test --package vibesql-executor`)
- [ ] No behavior changes (this is pure refactoring)

## Files to Modify

1. `crates/vibesql-storage/src/database/indexes.rs` - Add three methods to `IndexData`
2. `crates/vibesql-executor/src/select/executor/index_optimization/order_by.rs` - Fix line 132
3. `crates/vibesql-executor/src/select/executor/index_optimization/where_filter.rs` - Fix line 112
4. `crates/vibesql-executor/src/update/constraints.rs` - Fix line 96
5. `crates/vibesql-executor/src/insert/constraints.rs` - Fix line 210

## Verification Command

After implementation, verify no violations remain:
```bash
grep -r 'index_data\.data\.' crates/vibesql-executor/
# Should return no results
```

## Estimated Effort

**2-3 hours** (updated from 1-2 hours due to additional violations found)

## Dependencies

None (this is the foundation for subsequent phases)

## Next Phase

Once encapsulation is fixed, Phase 2 can integrate the disk-backed B+ tree implementation.

## Related Issues

- Part of index architecture cleanup
- Enables #1473 completion
- Prerequisite for proper B+ tree integration

---
**Curated by Loom** - Added two additional violations found via codebase analysis (`contains_key` calls in insert/update constraints)
