### ISSUE TITLE
Executor: 21 miscellaneous execution failures

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/vibesql#1636]
## Problem

21 SQLLogicTest files are failing with various execution errors not related to query result mismatches.

### 1. Type Mismatch Errors (3 failures)
```
✗ index/random/10/slt_good_1.test
Error: TypeMismatch { left: Varchar("mguub"), op: "unary +", right: Null }

Example queries attempting unary + operator on VARCHAR columns
```

**Root Cause**: The unary + operator implementation in `crates/vibesql-executor/src/evaluator/expressions/operators.rs:13-89` only handles numeric types (Integer, Smallint, Bigint, Float, Real, Double, Numeric) and NULL. Non-numeric types like VARCHAR are rejected with a TypeMismatch error.

**Implementation Location**: `eval_unary_op()` function at `crates/vibesql-executor/src/evaluator/expressions/operators.rs:13-89`

**Expected Behavior**: According to SQL standard behavior, unary + on non-numeric types should either:
- Return a type error (current behavior, which may be correct)
- OR attempt implicit casting to numeric type first (MySQL behavior)

Need to investigate what SQLLogicTest expects in these cases.

### 2. View Dependency Errors (1 failure)
```
✗ index/view/10/slt_good_1.test  
Error: Other("View or table 'VIEW_1_TAB0_153' is still in use by 1 view(s): VIEW_3_TAB0_153")

Issue: DROP VIEW failing when dependent views exist
```

**Root Cause**: The view dependency tracking in `crates/vibesql-catalog/src/store/advanced/views.rs:34-74` correctly identifies dependent views and returns `ViewInUse` error when CASCADE is not specified. However, the test is likely expecting the view to be dropped with CASCADE behavior, or the test setup is incorrect.

**Implementation Location**: 
- `drop_view()` at `crates/vibesql-catalog/src/store/advanced/views.rs:34-74`
- `find_dependent_views()` at `crates/vibesql-catalog/src/store/advanced/views.rs:76-93`
- Error conversion at `crates/vibesql-executor/src/errors.rs:682-686`

**Possible Solutions**:
1. The test may be using `DROP VIEW` without CASCADE when it should use `DROP VIEW ... CASCADE`
2. The dependency tracking may have a bug (e.g., case sensitivity issues in view name matching)
3. Need to verify the expected behavior in the original SQLite test case

### 3. Column Resolution Errors (1 failure)
```
✗ index/view/10/slt_good_2.test
Error: ColumnNotFound { column_name: "PK", table_name: "unknown", searched_tables: ["TAB0_302"], available_columns: ["column1", "column2"] }

Issue: Column name resolution failing in views
```

**Root Cause**: Column resolution is failing when querying from views. This suggests the view's column metadata or alias handling may not be preserved correctly when the view is materialized.

**Related Code Paths**:
- View execution and column resolution
- Table/view metadata retrieval
- Column name normalization (case sensitivity)

**Possible Issues**:
1. View column aliases not being stored/retrieved correctly
2. Case sensitivity mismatch between view definition and query
3. View's underlying table column mapping broken

### 4. Other Execution Errors (~16 failures)
Various other execution issues including:
- Expression evaluation errors
- Schema resolution issues  
- Constraint validation problems

Need to run individual test files to categorize these errors properly.

## Impact

- 21/623 tests failing (3.4% of test suite)
- Affects view functionality, type coercion, and expression evaluation
- Lower priority than the 555 query result mismatches (#1634)
- Higher priority than the 16 parser errors (#1635)

### Step 1: Categorize Remaining Errors
Run the failing tests individually to categorize the ~16 uncategorized failures:
```bash
# Get list of all 21 failing tests
./scripts/sqllogictest test <each-failing-test> --verbose
```

### Step 2: Fix Type Mismatch Errors
1. **Analyze expected behavior**: Check what SQLite/MySQL do with `+VARCHAR_COLUMN`
2. **Decision point**: Should we:
   - Keep the error (strict type checking)
   - Add implicit string-to-number conversion
   - Handle VARCHAR specially (return NULL or convert to 0)
3. **Update `eval_unary_op()`** in `crates/vibesql-executor/src/evaluator/expressions/operators.rs:13-89`

### Step 3: Fix View Dependency Errors
1. **Run the failing test** with verbose output to see exact SQL commands
2. **Check if CASCADE is needed**: Does the test expect `DROP VIEW ... CASCADE`?
3. **Debug dependency tracking**: Add logging to `find_dependent_views()` to see what views it's finding
4. **Verify case sensitivity**: Ensure view name matching respects the case_sensitive_identifiers setting

### Step 4: Fix Column Resolution Errors
1. **Investigate view column metadata storage**: Check how columns are stored when view is created
2. **Trace column resolution**: Add logging during SELECT from view to see where "PK" lookup fails
3. **Check alias handling**: Verify that column aliases in view definitions are preserved
4. **Test case sensitivity**: The error shows "unknown" table which suggests a metadata lookup issue

### Step 5: Address Remaining Errors
After categorizing the ~16 other errors, create focused subtasks for each category.

## Acceptance Criteria

- [ ] All 21 execution errors are categorized and documented
- [ ] Type mismatch errors (3 tests) are fixed with correct SQL semantics
- [ ] View dependency errors (1 test) are fixed 
- [ ] Column resolution errors (1 test) are fixed
- [ ] Remaining execution errors (~16 tests) have fixes or documented decisions
- [ ] All 21 tests pass
- [ ] No regressions in existing passing tests

## Test Commands

```bash
# Type mismatch example
./scripts/sqllogictest test third_party/sqllogictest/test/index/random/10/slt_good_1.test --verbose

# View dependency example  
./scripts/sqllogictest test third_party/sqllogictest/test/index/view/10/slt_good_1.test --verbose

# Column resolution example
./scripts/sqllogictest test third_party/sqllogictest/test/index/view/10/slt_good_2.test --verbose
```

## Related Issues

- #1634 - 555 query result mismatches (higher priority)
- #1635 - 16 parser errors
- #1606 - Overall SQLLogicTest progress tracking

## Technical References

**Key Files**:
- `crates/vibesql-executor/src/evaluator/expressions/operators.rs` - Unary operator evaluation
- `crates/vibesql-executor/src/evaluator/operators/arithmetic/mod.rs` - Arithmetic type coercion
- `crates/vibesql-catalog/src/store/advanced/views.rs` - View dependency tracking
- `crates/vibesql-executor/src/errors.rs` - Error type definitions
- `crates/vibesql-catalog/src/errors.rs` - Catalog error types

**Testing Infrastructure**:
- `./scripts/sqllogictest` - Test runner script
- `third_party/sqllogictest/test/` - Test file location

**Comment by rjwalters** [comment]
## Progress Update

Created PR #1656 which fixes the type mismatch errors (3 failures) related to unary + operator on text types.

**Fixed in PR #1656**:
- ✅ Type mismatch errors for unary + on VARCHAR/TEXT columns
- ✅ Added unit tests for the fix
- ✅ Follows SQLite behavior (identity operation)

**Remaining work for this issue**:
1. View dependency errors (1 failure) - 
2. Column resolution errors (1 failure) - 
3. Other execution errors (~16 failures) - need categorization

The remaining issues will require more investigation and may be addressed in separate PRs.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by rjwalters** [comment]
## Progress Update

While investigating this issue, discovered and fixed a **compilation blocker** that was preventing the sqllogictest suite from running.

### Fixed: Compilation Error

**PR #1659** - Fixes sqllogictest compilation error introduced by PR #1639

The sqllogictest adapter was missing handling for the  statement, causing compilation to fail with:
```
error[E0004]: non-exhaustive patterns: vibesql_ast::Statement::SetVariable(_) not covered
```

This was blocking all sqllogictest runs and preventing investigation of the execution failures tracked in this issue.

### Current Status  

- ✅ **MERGED** (PR #1637): Type mismatch errors for unary + on text types (3 failures fixed)
- ✅ **CREATED** (PR #1659): Compilation blocker fix  
- ⏳ **TODO**: Full sqllogictest run is currently executing to categorize remaining execution failures
- ⏳ **TODO**: Investigate and fix view dependency errors (1 failure)
- ⏳ **TODO**: Investigate and fix column resolution errors (1 failure)
- ⏳ **TODO**: Categorize and address other execution errors (~16 failures)

### Next Steps

Once PR #1659 is merged and the full test run completes, I'll categorize the remaining execution failures and create targeted fixes for each category.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by rjwalters** [comment]
## Progress Update

Created **PR #1665** to fix a case sensitivity bug in view dependency tracking.

### What Was Fixed

Fixed `does_from_clause_reference_table()` in `crates/vibesql-catalog/src/store/advanced/views.rs:124-141` to respect the `case_sensitive_identifiers` setting when comparing table/view names.

**Problem**: The view dependency checker was using case-sensitive string comparison even when `case_sensitive_identifiers` was false, causing incorrect dependency detection.

**Solution**: Now uses case-insensitive comparison (uppercase) when `case_sensitive_identifiers` is false, matching the behavior of `get_view()` and `drop_view()`.

### Current Status

- ✅ **MERGED** (PR #1637): Type mismatch errors for unary + on text types (3 failures fixed)
- ✅ **CREATED** (PR #1659): Compilation blocker fix - MERGED
- ✅ **CREATED** (PR #1665): Case sensitivity fix in view dependency tracking
- ⏳ **IN PROGRESS**: Full test suite running to categorize remaining execution failures
- ⏳ **TODO**: Investigate column resolution errors in view queries
- ⏳ **TODO**: Categorize and fix remaining ~15-18 execution errors

### Next Steps

Once PR #1665 is reviewed/merged and test results are available, will continue investigating:
1. Column resolution errors (1 failure) - `ColumnNotFound` errors when querying views
2. Remaining execution errors based on full test suite categorization

The case sensitivity fix is an improvement to view handling consistency, though its impact on the specific 21 execution failures requires further testing to verify.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by rjwalters** [comment]
## Progress Update - Current Test Results

Ran full sqllogictest suite to assess current state of execution failures.

### Summary
- **Started with**: 21 execution failures (original issue scope)
- **Fixed**: 3 type mismatch errors via PR #1637 ✅
- **Current**: 18 execution failures
- **Status**: Issue has evolved - new error categories and significant changes in error distribution

### Current Execution Errors Breakdown

#### 1. ColumnNotFound Errors: 11 failures ⚠️ GREW 10x
All failures are in view-related index tests with the same pattern:
```
ColumnNotFound { column_name: "PK", table_name: "unknown", searched_tables: ["TAB0_XXX"], available_columns: ["column1", "column2"] }
```

**Affected files**:
- `index/view/10/slt_good_2.test` through `slt_good_7.test` (6 files)
- `index/view/100/slt_good_0.test`, `slt_good_1.test`, `slt_good_3.test`, `slt_good_5.test` (4 files)
- `index/view/10000/slt_good_0.test` (1 file)

**Note**: Original issue mentioned only 1 ColumnNotFound error. This 10x increase is concerning.

#### 2. View Not Found Errors: 4 failures ⚠️ NEW
```
Other("View 'VIEW_X_TAB0_Y' not found")
```

**Affected files**:
- `index/view/10/slt_good_1.test`
- `index/view/100/slt_good_2.test`, `slt_good_4.test`
- `index/view/1000/slt_good_0.test`

**Note**: Original issue mentioned "View still in use" errors - these are different. The error type has changed from dependency tracking to view lookup.

#### 3. DivisionByZero Errors: 2 failures ⚠️ NEW
**Affected files**:
- `random/aggregates/slt_good_121.test`
- `random/expr/slt_good_53.test`

#### 4. UnsupportedExpression Error: 1 failure ⚠️ NEW
```
UnsupportedExpression("Aggregate functions should be evaluated in aggregation context")
```
**Affected file**: `random/expr/slt_good_46.test`

### Additional Parse Errors (15 failures)
These are tracked separately from execution errors:
- 14 `random/groupby` tests: `Expected expression, found SessionVariable("sql_mode")`
- 1 `ddl/createtable/createtable1.test`: `Expected RParen, found LParen`

### Analysis & Next Steps

**Key Concern**: The spike in ColumnNotFound errors (1 → 11) and change in view error types suggests:
1. Possible regression from PR #1665 (case sensitivity fix)
2. Pre-existing issues now being revealed by improved test coverage
3. View column metadata handling needs investigation

**Investigation priorities**:
1. 🔍 **Immediate**: Investigate ColumnNotFound spike - why did view tests start failing?
2. 🔍 **High**: Investigate "View not found" vs "View still in use" error change
3. 📋 **Medium**: Address DivisionByZero handling
4. 📋 **Medium**: Fix aggregate function context validation
5. 📋 **Low**: Session variable parsing in GROUP BY context

**Recommendation**: Cannot close this issue yet. The error landscape has shifted significantly, and the view-related test failures (15 out of 18 execution errors) need root cause analysis before proceeding.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
